# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Azure Pipelines
  demands:
  - maven
  - vstest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: latest


- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: 'Infraestructura'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  inputs:
    command: 'plan'
    workingDirectory: 'Infraestructura'
    allowTelemetryCollection: true

- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
  displayName: 'terraform Apply'
  inputs:
    command: apply
    workingDirectory: Infraestructura
    commandOptions: '--auto-approve'

- task: TerraformCLI@0
  inputs:
    command: 'destroy'
    workingDirectory: 'Infraestructura'
    commandOptions: '--auto-approve'
    allowTelemetryCollection: true