# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Azure Pipelines
  demands:
  - maven
  - vstest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'AzureDevops'
    organization: 'psonarcloud'
    scannerMode: 'Other'

- task: Maven@4
  displayName: 'Maven ApiRest/pom.xml'
  inputs:
    mavenPomFile: '$(System.DefaultWorkingDirectory)/ApiRest/pom.xml'
    publishJUnitResults: false
    jdkVersionOption: '1.11'
    sonarQubeRunAnalysis: true

- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: '**\*test*.java'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)/Imagen'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: 'ApiRest/target/pichincha-0.0.1-SNAPSHOT.jar'
    TargetFolder: '$(build.artifactstagingdirectory)/Imagen'
  condition: succeededOrFailed()

- task: CopyFiles@2
  displayName: 'Copy Files Docker to: $(build.artifactstagingdirectory) '
  inputs:
    SourceFolder: Docker
    Contents: '*'
    TargetFolder: '$(build.artifactstagingdirectory)/Imagen/ApiRest/target'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: imagen'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/Imagen/ApiRest/target'
    ArtifactName: imagen
